### ISSUE TITLE
new version of lichess released = extension broken

### ISSUE THREAD

**Issue by ornicar** [vincentsimard/dmitlichess#1]
Hi,

As I told you recently, lichess got a major upgrade. The HTML has changed quite a bit and as a result your most excellent extension is not working anymore.

Just a heads up in case you want to update it. The actual frontend of lichess is now stable and may be built upon.

**Comment by Parakovsky** [comment]
> OH YEAH!! Dmitri voice is back. Sounds so good!

we need to get this back to work again gentelmans
