### ISSUE TITLE
dmitchess on chrome?

### ISSUE THREAD

**Issue by ddugovic** [vincentsimard/dmitlichess#31]
> i saw some people playing with dmitchess sounds on lichess, i installed it but it doesnt seem to work on chrome web browser. Does anyone have the same issues, or does someknow know a solution to this?

https://lichess.org/forum/lichess-feedback/dmitchess-on-chrome

**Comment by vincentsimard** [comment]
Can't reproduce. lichess.org/@/UndressTheHess has resolved the issue on his side
